# Generated by Django 5.1.4 on 2025-03-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('service_no', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
                ('seats_available', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200)),
                ('phno', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='booking_history',
            fields=[
                ('ticket_no', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_seats', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('service_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='busapp.bus')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='busapp.customers')),
            ],
        ),
    ]
