# Generated by Django 5.1.4 on 2025-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_booking_history_travelling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='ticket_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
